server {
    listen 80;
    server_name localhost;

    #Monitorización para el nodo 10.10.10.30
    location /nginx_status {
        stub_status;
        allow 10.10.10.30; 
        deny all;
    }

    # Configuración del Frontal
    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }
}
