server {
    listen 80;
    server_name localhost;

    #Monitorización para el nodo 10.10.10.30
    location /nginx_status {
        stub_status;
        allow 10.10.10.30; 
        deny all;
    }

    # Configuración del Frontal
    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }
# Procesamiento de PHP para el CMS
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php-fpm.sock; # Asegúrate de que PHP-FPM esté instalado
    }

    # Bloquear acceso a archivos sensibles del CMS
    location ~ /\.ht {
        deny all;
    }
}
