# Definición del clúster para redundancia
upstream cms_backend {
    server 192.168.100.21; # Web-01 (Red main)
    server 192.168.100.22; # Web-02 (Red main)
}

server {
    listen 80;
    #Solo se accede a través del balanceador desde internet
    server_name fake-enterprise.com; 

    location / {
        proxy_pass http://cms_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /nginx_status {
        stub_status;
        allow 10.10.10.30; # IP del nodo de monitorización en la red internal
        deny all;
    }
}
